# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_rating', models.IntegerField(verbose_name='Full rating of User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, verbose_name='Name of category')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='Action that changed the rating')),
                ('value', models.IntegerField(editable=False, verbose_name='Value on which the rating has changed')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of rating change')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating', models.IntegerField(verbose_name='Rating of User by category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.CategoryRating')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.AllRating')),
            ],
        ),
        migrations.AddField(
            model_name='historyrating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Rating'),
        ),
    ]
