# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import eben.tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('date_added', models.DateTimeField(verbose_name='Date added')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('status', models.CharField(choices=[('new', 'new'), ('doing', 'doing'), ('verifying', 'verifying'), ('returned', 'returned'), ('done', 'done')], default='new', max_length=9, verbose_name='Task status')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('author', models.ForeignKey(on_delete=models.SET(eben.tasks.models.get_sentinel_user), related_name='task_author', to=settings.AUTH_USER_MODEL, verbose_name='Task author')),
                ('doer', models.ForeignKey(on_delete=models.SET(eben.tasks.models.get_sentinel_user), related_name='task_doer', to=settings.AUTH_USER_MODEL, verbose_name='Doer')),
                ('files', models.ManyToManyField(related_name='task_files', to='files.File', verbose_name='Attached files')),
                ('solution_files', models.ManyToManyField(related_name='task_solution_files', to='files.File', verbose_name='Attached solution files')),
            ],
        ),
    ]
