# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Picture of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, max_length=200, verbose_name='Short info about User'),
        ),
    ]
